docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/landr
      publish: true
npm:
  run: true
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - 12
